### ISSUE TITLE
Configure wifi SSID and PSK in /boot/system-connections/resin-wifi file

### ISSUE THREAD

**Issue by lekkas** [resin-io-playground/resin-toolbox#3]
This is a `yaml` or `.ini` file i believe, there is an example of this here: 

https://github.com/resin-os/meta-resin/issues/324

**Comment by shaunmulligan** [comment]
@lekkas this issue was closed by #16 right?

**Comment by lekkas** [comment]
@shaunmulligan right, closing it now, thanks!
