### ISSUE TITLE
[proposal] add a scan function, that scans and fines resinOS devices.

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io-playground/resin-toolbox#39]
It would be useful to have a simple scan command that would just keep scanning for the device connect, and when it finds one, it can print out some info about the device, like IP address, hostname, maybe docker info?

**Comment by lekkas** [comment]
Yeah that makes sense 👍

**Comment by lekkas** [comment]
Implemented: https://github.com/resin-os/resin-device-toolbox/issues/13
