### ISSUE TITLE
publish resin-toolbox on NPM

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io-playground/resin-toolbox#40]

**Comment by lekkas** [comment]
@shaunmulligan have we decided on names for:
- the published module
- the cli command

The can both be `resin-toolbox` or be different, e.g. `resin-cli` / `resin` for our Resin CLI

**Comment by shaunmulligan** [comment]
@lekkas let's go with `resin-device-toolbox` as the module name and `rdt` as the command

**Comment by lekkas** [comment]
Published `resin-device-toolbox@0.0.1` which can be invoked by running `rdt`
